import js from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier";
import globals from "globals";

export default [
  {
    ignores: [
      ".yarn/**",
      "node_modules/**",
      ".aws-sam/**",
      "dist/**",
      "build/**",
      "*.cjs",
      "*.config.cjs",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.mjs", "**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...globals.node },
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: { globalReturn: false },
      },
    },
    rules: {
      "no-unused-vars": [
        "error",
        { args: "all", argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-undef": "error",
      "no-use-before-define": ["error", { functions: false, variables: true, classes: true }],
      "no-var": "error",
      "prefer-const": "error",
      "prefer-arrow-callback": "off",
      "prefer-template": "warn",
      eqeqeq: ["error", "always", { null: "ignore" }],
      curly: ["error", "all"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-return-await": "off",
      "require-await": "warn",
      "no-throw-literal": "error",
      "no-unused-expressions": "off",
      "no-console": "off",
      strict: ["error", "global"],
      "no-shadow": ["warn", { builtinGlobals: true, hoist: "all" }],
      "no-redeclare": "error",
      "no-duplicate-imports": "error",
      "no-array-constructor": "error",
      "no-new-object": "error",
      "object-shorthand": ["warn", "always", { avoidQuotes: true }],
      "quote-props": ["warn", "as-needed", { keywords: true, unnecessary: true }],
      "prefer-destructuring": "off",
      "no-nested-ternary": "warn",
      "no-unneeded-ternary": "warn",
      "no-else-return": "warn",
      "no-lonely-if": "warn",
      "no-useless-return": "error",
      "no-useless-concat": "error",
      "no-useless-rename": "warn",
      "no-extra-bind": "error",
      "no-extra-boolean-cast": "error",
      "no-extra-semi": "error",
      "no-floating-decimal": "error",
      "no-multi-spaces": "error",
      "no-multiple-empty-lines": ["error", { max: 1, maxEOF: 1 }],
      "no-trailing-spaces": "error",
      "no-unreachable": "error",
      "no-constant-condition": "warn",
      "no-empty": "warn",
      "no-labels": "error",
      "no-extra-label": "error",
      "no-lone-blocks": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-with": "error",
      radix: "error",
      yoda: ["error", "never", { exceptRange: true }],
      "block-scoped-var": "error",
      "default-case": "warn",
      "dot-notation": "warn",
      "no-caller": "error",
      "no-iterator": "error",
      "no-proto": "error",
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-void": "error",
      "no-delete-var": "error",
      "no-label-var": "error",
      "no-restricted-syntax": [
        "error",
        { selector: "WithStatement", message: "`with` is not allowed." },
        { selector: "LabeledStatement", message: "Labels are not allowed." },
      ],
    },
  },
  eslintConfigPrettier,
];
